import type { Metadata } from "next";
import ClientSide from "@/components/ClientSide";
import "./styles/global.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning> {/* Prevents hydration mismatch */}
        <ClientSide>{children}</ClientSide>
      </body>
    </html>
  );
}
